testConn: zhy
server:    port: 8764
eureka:    client:       serviceUrl:          defaultZone: http://localhost:8761/eureka/
spring: 
    datasource: 
        name: test
        url: jdbc:oracle:thin:@10.226.95.34:1521:moauat
        username: moa
        password: workout
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20